//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewCustomer_BanHangLuuNiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int MaCT { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string ChatLieu { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<double> KhoiLuong { get; set; }
        public string MoTa { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
