//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewCustomer_BanHangLuuNiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string SDTKH { get; set; }
        public string DiaChiKH { get; set; }
        public int MaDH { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
